version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start

  test:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=test
    command: npm test
    volumes:
      - ./data:/app/data